export const STEPS = {
  NEEDS_ANALYSIS: "Needs Analysis",
  OBJECTIVE: "Objective",
  FINAL_ASSESSMENT_STRATEGY: "Final Assessment Strategy",
  COURSE_STRUCTURE: "Course Structure",
  COURSE_STRATEGY_DOCUMENT: "Course Strategy Document",
  STORYBOARD: "Storyboard",
};

export const STEPS_SEQUENCE = [
  STEPS.NEEDS_ANALYSIS,
  STEPS.OBJECTIVE,
  STEPS.FINAL_ASSESSMENT_STRATEGY,
  STEPS.COURSE_STRUCTURE,
  STEPS.COURSE_STRATEGY_DOCUMENT,
  STEPS.STORYBOARD,
];